# Big thanks and love for using my plugins! ^^

#|--------------------------------------------------------------------------------------------------------------------|#
# Plugin: Economy
# Author: https://www.mc-market.org/members/89497/
# Description: Plugin for handling in-game economy.
# Dependencies:
#   -> MySQL Database
#   -> PLJRApi
#   -> Vault (https://www.spigotmc.org/resources/vault.34315/)
#|--------------------------------------------------------------------------------------------------------------------|#

###############\
# MySQL Setup ##############################################################################################\
############### This is the most important part, as the plugin can not work without proper MySQL Database. # \
              ##############################################################################################  \
mysql:
  enabled: false #-> Should we use this database instead of the one configured in PLJRApi config.yml?
  host: "127.0.0.1"
  port: "3306"
  database: "db"
  username: "root"
  password: ""
#|--------------------------------------------------------------------------------------------------------------------|#

##############\
# Lang Setup ################################################################\
############## Here, you can customize messages, send by the plugin itself. # \
             ################################################################  \

help:
  - ""
  - "§a§lEconomy Help v${project.version}"
  - ""
  - "§e/economy §8» §fDisplays your current balance."
  - "§e/economy help §8» §fDisplays this message."
  - "§e/economy balance <player> §8» §fDisplays current balance of player."
  - "§e/economy send <player> <amount> §8» §fSends player amount of money."

admin-help:
  - ""
  - "§a§lEconomy Admin-Help v${project.version}"
  - ""
  - "§e/aeconomy help §8» §fDisplays this message."
  - "§e/aeconomy set <player> <amount> §8» §fSets player's balance."
  - "§e/aeconomy add <player> <amount> §8» §fAdds money to player's balance."
  - "§e/aeconomy remove <player> <amount> §8» §fRemoves money from player's balance."

lang:
  CONSOLE_NAME: "Console"
  NO_CONSOLE: "§cThis command is for in-game use only!"
  NO_POSITIVE_NUMBER: "§aEconomy §8» §fThe number must be positive!"
  ECONOMY_SUCCESS: "§aEconomy §8» §fYour balance is: §b$%money§f."
  ECONOMY_BALANCE_SUCCESS: "§aEconomy §8» §fBalance of §b%player §fis: §b$%money§f."
  ECONOMY_SEND_SUCCESS: "§aEconomy §8» §fSuccessfully send §b%money §fto §b%player§f."
  ECONOMY_SEND_FAILURE_TOO_MUCH: "§aEconomy §8» §fYou don't have enough money to do this!"
  ECONOMY_SEND_SUCCESS_NOTIFY: "§aEconomy §8» §fYou received §b%money §ffrom §b%player§f."
  AECONOMY_SET_SUCCESS: "§aEconomy §8» §fSuccessfully set balance of §b%player §fto §b%money§f."
  AECONOMY_SET_SUCCESS_NOTIFY: "§aEconomy §8» §fYour balance has been set to §b%money §fby §b%player§f."
  AECONOMY_ADD_SUCCESS: "§aEconomy §8» §fSuccessfully added §b%money §fto §b%player's §fbalance."
  AECONOMY_ADD_SUCCESS_NOTIFY: "§aEconomy §8» §b%money §fhas been added to your balance by §b%player§f."
  AECONOMY_REMOVE_SUCCESS: "§aEconomy §8» §fSuccessfully removed §b%money §ffrom §b%player's §fbalance."
  AECONOMY_REMOVE_FAILURE_TOO_MUCH: "§aEconomy §8» §b%player §fdoes not have enough money!"
  AECONOMY_REMOVE_SUCCESS_NOTIFY: "§aEconomy §8» §b%money §fhas been removed from your balance by §b%player§f."

  # Vault responses, they are not shown in commands, but you can still customize them and use in your plugin perhaps.
  VAULT_WITHDRAW_PLAYER_FAILURE_NO_ACCOUNT: "§c%player does not have an account!"
  VAULT_WITHDRAW_PLAYER_FAILURE_TOO_MUCH: "§c%player does not have enough money."
  VAULT_DEPOSIT_PLAYER_FAILURE_NO_ACCOUNT: "§c%player does not have an account!"
  VAULT_NOT_IMPLEMENTED: "§cThis functions is not implemented!"
#|--------------------------------------------------------------------------------------------------------------------|#