# Big thanks and love for using my plugins! ^^

#|--------------------------------------------------------------------------------------------------------------------|#
# Plugin: Economy
# Author: https://www.mc-market.org/members/89497/
# Description: Plugin for handling in-game economy.
# Dependencies:
#   -> MySQL Database
#   -> PLJRApi-Spigot
#   -> Vault (https://www.spigotmc.org/resources/vault.34315/)
#|--------------------------------------------------------------------------------------------------------------------|#

###############\
# MySQL Setup ##############################################################################################\
############### This is the most important part, as the plugin can not work without proper MySQL Database. # \
              ##############################################################################################  \
mysql:
  host: "127.0.0.1"
  port: "3306"
  database: "db"
  username: "root"
  password: ""

# Detailed documentation about this configuration: https://github.com/brettwooldridge/HikariCP#configuration-knobs-baby
mysql-settings:
  maximumPoolSize: 16
  maximumIdle: 2
  maxLifetime: 1800000
  connectionTimeout: 30000
  cachePrepStmts: true
  prepStmtCacheSize: 250
  prepStmtCacheSqlLimit: 2048
#|--------------------------------------------------------------------------------------------------------------------|#

##################\
# Settings Setup #############################################################\
################## Here, you can enable or disable functions of this plugin. # \
                 #############################################################  \
settings:
  default-balance: 10 #-> What should be the initial amount of currency for new players?
  death-lose: 2 #-> How many percent of player's current balance should he lose per death?
  death-lose-player: 10 #-> How many percent of player's current balance should he lose per death by player?
#|--------------------------------------------------------------------------------------------------------------------|#